# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Evan Gambill - Portfolio 
tagline:          'Creator and Problem Solver'
description:      'This is an online portfolio for the work done by Evan Gambill.'
url:              
baseurl:          https://evanbg42.github.io/portfolio-site/

author:
  name:           'Evan Gambill'
  url:             

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/EvanBG42/portfolio-site
