# Dependencies
highlighter:      rouge 

# Permalinks
permalink:        pretty

# Setup
title:            Evan Gambill - Portfolio 
tagline:          'Creator and Problem Solver'
description:      'This is an online portfolio for the work done by Evan Gambill.'
url:              
baseurl:          https://evanbg42.github.io/portfolio-site/

author:
  name:           'Evan Gambill'
  url:             

paginate:         5

include: ['pages']

# Custom vars
version:          0.1

github:
  repo:           https://github.com/EvanBG42/portfolio-site
